/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package KIJ;


import javax.swing.DefaultListModel;

/**
 *
 * @author alif.sip
 */
public class ChatField extends javax.swing.JFrame {

    /**
     * Creates new form ChatField
     */
    private Client client;
    public String username;
    public String ip;
    public int port;
    public String sendTo;
   
    
    public ChatField() {
        initComponents();  
    }

    ChatField(Client client, String SendTo) {
        initComponents();
        this.sendTo = SendTo;
        jLabel2.setText("@" + sendTo);
        this.client = client;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendto3 = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        chatField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dconn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        sendto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendto3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 60, 30));

        outputArea.setEditable(false);
        outputArea.setBackground(new java.awt.Color(204, 204, 204));
        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 290, 170));

        chatField.setBackground(new java.awt.Color(204, 204, 204));
        chatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatFieldActionPerformed(evt);
            }
        });
        getContentPane().add(chatField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("@User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        dconn.setBackground(new java.awt.Color(255, 0, 102));
        dconn.setText("Close Chat");
        dconn.setToolTipText("");
        dconn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dconnActionPerformed(evt);
            }
        });
        getContentPane().add(dconn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 110, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Desain ChatField Client.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
            client.sendMessage("TALKTO " + sendTo + ":" + chatField.getText() + "\r\n");
            append(username + ":" + chatField.getText() + "\n");
            chatField.setText("");
           
    }//GEN-LAST:event_sendButtonActionPerformed

    private void chatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatFieldActionPerformed

    }//GEN-LAST:event_chatFieldActionPerformed

    private void sendto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendto3ActionPerformed

    private void dconnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dconnActionPerformed
        // TODO add your handling code here:
        //client.sendMessage("BYE\r\n");
        this.dispose();
    }//GEN-LAST:event_dconnActionPerformed

    void append(String str) 
    {
		outputArea.append(str);
		outputArea.setCaretPosition(outputArea.getText().length());
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ChatField().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatField;
    private javax.swing.JButton dconn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField sendto;
    private javax.swing.JTextField sendto1;
    private javax.swing.JTextField sendto3;
    // End of variables declaration//GEN-END:variables
}
